FROM python:3.7-slim AS build
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

### INFO: 
# What is distroless: https://medium.com/better-programming/how-to-harden-your-containers-with-distroless-docker-images-c2abd7c71fdb
# Google Base Images: https://github.com/GoogleContainerTools/distroless/
FROM gcr.io/distroless/python3-debian10
COPY src/ /app/
COPY --from=build /usr/local/lib/python3.7/site-packages /usr/local/lib/python3.7/site-packages
WORKDIR /app
ENV PYTHONPATH=/usr/local/lib/python3.7/site-packages
CMD ["/app/azure-copy-tool.py"]